server:
  port: 8183
spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    password: root
#    url: jdbc:mariadb://localhost:3306/credentialdb
#    username: root
  application:
       name: login-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
   import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}


eureka:
  client:
      register-with-eureka: true
      service-url:
         defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/} 

logging:
    file:
      name: login-service.log
management:
  endpoints:
    web:
      exposure:
        include: "*"            